# Generated by Django 5.1.2 on 2025-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(choices=[('AG', 'AGENDADA'), ('AT', 'ATENDIDA'), ('CA', 'CANCELADA'), ('NA', 'NO ATENDIDA')], default='AGENDADA', max_length=20, verbose_name='Estado de la cita'),
        ),
    ]
