# Generated by Django 5.1.2 on 2025-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='codigo',
            field=models.CharField(default=23000, max_length=20, unique=True, verbose_name='Codigo de la especialidad médica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción de la especialidad médica'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre de la especialidad médica'),
        ),
    ]
