# Generated by Django 5.1.2 on 2025-03-06 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0002_alter_citamedica_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='enrolado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('MED', 'Medico'), ('PAC', 'Paciente'), ('AUXA', 'Auxiliar Administrativo'), ('AUXE', 'Auxiliar Enfermeria'), ('ADM', 'Administrador de Sistema')], default='Paciente', max_length=20, verbose_name='Rol en la empresa'),
        ),
        migrations.CreateModel(
            name='AgendaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('turno_disponible', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='medica_app.medico')),
            ],
        ),
    ]
