# Generated by Django 5.1.2 on 2025-04-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0002_especialidad_codigo_alter_especialidad_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamedica',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
