# Generated by Django 5.1.2 on 2025-04-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0003_agendamedica_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='ciudad',
            field=models.CharField(default='SOACHA', max_length=150, verbose_name='Ciudad de asentamiento de la sede'),
        ),
        migrations.AddField(
            model_name='sede',
            name='direccion',
            field=models.CharField(default='0', max_length=150, verbose_name='Direccion de la sede'),
        ),
        migrations.AddField(
            model_name='sede',
            name='telefono',
            field=models.CharField(default='0', max_length=150, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='descripcion',
            field=models.TextField(default='0', verbose_name='Descripción de la sede'),
        ),
    ]
