# Generated by Django 5.1.2 on 2025-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0003_remove_usuario_enrolado_usuario_rol_agendamedica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradorsistema',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('MED', 'Medico'), ('PAC', 'Paciente'), ('AUXA', 'Auxiliar Administrativo'), ('AUXE', 'Auxiliar Enfermeria'), ('ADM', 'Administrador de Sistema'), ('ND', 'No asignado')], default='No asignado', max_length=20, verbose_name='Rol en la empresa'),
        ),
    ]
