# Generated by Django 5.1.2 on 2025-04-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0004_sede_ciudad_sede_direccion_sede_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código del consultorio')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del consultorio')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultorios', to='medica_app.especialidad')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultorios', to='medica_app.sede')),
            ],
            options={
                'db_table': 'consultorios',
            },
        ),
    ]
