# Generated by Django 5.1.2 on 2025-04-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0005_consultorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamedica',
            old_name='turno_disponible',
            new_name='disponible',
        ),
    ]
