# Generated by Django 5.1.2 on 2025-04-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0006_rename_turno_disponible_agendamedica_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliaradministrativo',
            name='fecha_ingreso',
            field=models.DateField(auto_now=True, verbose_name='Fecha de ingreso institucional'),
        ),
    ]
