# Generated by Django 5.1.2 on 2025-04-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medica_app', '0007_alter_auxiliaradministrativo_fecha_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auxiliaradministrativo',
            old_name='fecha_ingreso',
            new_name='fecha_ing',
        ),
    ]
