# Generated by Django 5.1.2 on 2025-04-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_autorizacion_codigo_alter_citamedica_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='ciudad',
        ),
    ]
